pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Just saying hello from GITHUB"'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    sh 'echo "Just another bs print line."'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "Just a hello from the Deliver stage."'
            }
        }
    }
}
