pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Just saying hello from GITHUB'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'Just a hello from the Deliver stage'
            }
        }
    }
}
